# Generated by Django 6.0.4 on 2026-04-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
