# Generated by Django 6.0.4 on 2026-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_reviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
